export const musicQuestions = [
    {
        id: "q1",
        song: "Arriey's Song",
        artist: 'Tommy heavenly6',
        anime: 'The Secret World of Arrietty',
        url: '/questions_media/music/arriey_s song_.webm', 
    },
    {
        id: "q2",
        song: 'Laputa',
        artist: 'Machico',
        anime: 'Castle in the Sky',
        url: '/questions_media/music/Castle in the sky - Laputa.webm', 
    },
    {
        id: "q3",
        song: 'Fine on the Outside',
        artist: 'Konomi Suzuki',
        anime: 'No Game No Life',
        url: '/questions_media/music/Fine on the outside.webm', 
    },
    {
        id: "q4",
        song: 'Sayonara no natsu',
        artist: 'Official Hige Dandism',
        anime: 'From Up on Poppy hill',
        url: '/questions_media/music/From up on the hill - Sayonara no natsu.webm', 
    },
    {
        id: "q5",
        song: 'itsumo nando demo',
        artist: 'Minami Kuribayashi',
        anime: 'The Devil is a Part Timer',
        url: '/questions_media/music/itsumo nando demo.webm', 
    },
    {
        id: "q6",
        song: "Kaze ni Naru",
        artist: 'Tommy heavenly6',
        anime: 'Gintama',
        url: '/questions_media/music/kaze ni naru_.webm', 
    },
    {
        id: "q7",
        song: 'nobody knows your heart',
        artist: 'Machico',
        anime: 'Castle in the Sky',
        url: '/questions_media/music/nobody knows your heart.webm', 
    },
    {
        id: "q8",
        song: 'on the cliff by the sea',
        artist: 'Konomi Suzuki',
        anime: 'Ponyo',
        url: '/questions_media/music/ponyo on the cliff by the sea.webm', 
    },
    {
        id: "q9",
        song: 'Sekai no yakusoku',
        artist: 'Official Hige Dandism',
        anime: 'From Up on Poppy hill',
        url: '/questions_media/music/Sekai no yakusoku_.webm', 
    },
    {
        id: "q10",
        song: 'Town with ocean view',
        artist: 'Minami Kuribayashi',
        anime: 'The Devil is a Part Timer',
        url: '/questions_media/music/Town with ocean view.webm', 
    },
]
